import { DOMNode, ExporterArguments, TextWriter } from "@conjure/core";
import { join } from "path";

function writeHeader(wks: DOMNode, config: string, platform: string, writer: TextWriter)
{
    writer.write(`# Generated by Conjure`);
    writer.write(`# Workspace: ${wks.getName()} - Configuration ${config}:${platform}`);
}

function writeWorkspace(wks: DOMNode, _args: ExporterArguments, config: string, platform: string) {
    const filename = `${wks.getName()}_${config}_${platform}.ninja`;
    const wksFileLocation = join(wks.location, filename);
    const file = new TextWriter(wksFileLocation);
    writeHeader(wks, config, platform, file);
    file.close();
}

export function workspace(wks: DOMNode, args: ExporterArguments) {
    const configs: string[] = wks.configurations;
    const platforms: string[] = wks.platforms;

    configs.forEach(config => {
        platforms.forEach(platform => {
           writeWorkspace(wks, args, config, platform); 
        });
    });
}